/** Publieke afbeeldingen — stabiele paden zonder spaties */
export const IMG = {
  buiten: {
    gevelRamen: "/assets/buiten/gevel-ramen.jpeg",
  },
  renovatie: {
    badkamer: "/assets/renovatie/badkamer.jpeg",
    living: "/assets/renovatie/living.jpeg",
    keuken: "/assets/renovatie/keuken.jpeg",
    slaapkamer: "/assets/renovatie/slaapkamer.jpeg",
    slaapkamer2: "/assets/renovatie/slaapkamer2.jpeg",
    traphal: "/assets/renovatie/traphal.jpeg",
  },
  voorNa: {
    livingVoor: "/assets/voor-na/living-voor.jpeg",
    livingNa: "/assets/voor-na/living-na.jpeg",
    badkamerVoor: "/assets/voor-na/badkamer-voor.jpeg",
    badkamerNa: "/assets/voor-na/badkamer-na.jpeg",
    renovatieVoor: "/assets/voor-na/renovatie-voor.jpeg",
    renovatieNa: "/assets/voor-na/renovatie-na.jpeg",
    wcVoor: "/assets/voor-na/wc-voor.jpeg",
    wcNa: "/assets/voor-na/wc-na.jpeg",
    deur: "/assets/voor-na/deur-voor-na.jpeg",
    hoek: "/assets/voor-na/hoek-voor-na.jpeg",
    livingVoorNa: "/assets/voor-na/living-voor-na.jpeg",
    buitenDeurVoor: "/assets/voor-na/buiten-deur-voor.jpeg",
    buitenDeurNa: "/assets/voor-na/buiten-deur-na.jpeg",
    buitenRaamVoor: "/assets/voor-na/buiten-raam-voor.jpeg",
    buitenRaamNa: "/assets/voor-na/buiten-raam-na.jpeg",
    buitenGevelVoor: "/assets/voor-na/buiten-gevel-voor.jpeg",
    buitenGevelNa: "/assets/voor-na/buiten-gevel-na.jpeg",
    buitenZijgevelVoor: "/assets/buiten/zijgevel-voor.jpeg",
    buitenZijgevelNa: "/assets/buiten/zijgevel-na.jpeg",
    heroGevel: "/assets/voor-na/huis-zonder-logo.jpeg",
    trapVoor: "/assets/voor-na/trap-voor.jpeg",
    trapNa: "/assets/voor-na/trap-na.jpeg",
    trapVoor2: "/assets/voor-na/trap-voor2.jpeg",
    trapNa2: "/assets/voor-na/trap-na2.jpeg",
  },
} as const;
